
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2022.2.4/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        //wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/3.29.0-rc1/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2022.2.4/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        //wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/3.29.0-rc1/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-sbeo4x"
      binary: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-sbeo4x"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-sbeo4x'
        
        Run Build Command(s): "C:/Users/Outros/3ºAno-2ºSemestre/DA/Aula 1/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_dbb90/fast
        C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_dbb90.dir\\build.make CMakeFiles/cmTC_dbb90.dir/build
        mingw32-make[1]: Entering directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-sbeo4x'
        mingw32-make[1]: *** No rule to make target 'C:/Users/Outros/3┬║Ano-2┬║Semestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeCCompilerABI.c', needed by 'CMakeFiles/cmTC_dbb90.dir/CMakeCCompilerABI.c.obj'.  Stop.
        mingw32-make[1]: Leaving directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-sbeo4x'
        mingw32-make: *** [Makefile:126: cmTC_dbb90/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/JetBrains/CLion 2022.2.4/bin/mingw/bin/gcc.exe"
    directories:
      source: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ekuw8f"
      binary: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ekuw8f"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ekuw8f'
        
        Run Build Command(s): "C:/Users/Outros/3ºAno-2ºSemestre/DA/Aula 1/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_46d1e/fast
        C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_46d1e.dir\\build.make CMakeFiles/cmTC_46d1e.dir/build
        mingw32-make[1]: Entering directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ekuw8f'
        process_begin: CreateProcess(NULL, "C:\\Users\\Outros\\3┬║Ano-2┬║Semestre\\DA\\Aula 1\\bin\\cmake.exe" -E cmake_echo_color --switch= --progress-dir=\\\\wsl$\\Ubuntu-20.04\\root\\1st_DAProject\\1stDA_Project\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-ekuw8f\\CMakeFiles --progress-num=1 "Building C object CMakeFiles/cmTC_46d1e.dir/testCCompiler.c.obj", ...) failed.
        make (e=2): O sistema nÒo conseguiu localizar o ficheiro especificado.\x0d
        mingw32-make[1]: *** [CMakeFiles\\cmTC_46d1e.dir\\build.make:76: CMakeFiles/cmTC_46d1e.dir/testCCompiler.c.obj] Error 2
        mingw32-make[1]: Leaving directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ekuw8f'
        mingw32-make: *** [Makefile:126: cmTC_46d1e/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2022.2.4/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        //wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/3.29.0-rc1/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2022.2.4/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        //wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/3.29.0-rc1/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7ltnyt"
      binary: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7ltnyt"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7ltnyt'
        
        Run Build Command(s): "C:/Users/Outros/3ºAno-2ºSemestre/DA/Aula 1/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_addd9/fast
        C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_addd9.dir\\build.make CMakeFiles/cmTC_addd9.dir/build
        mingw32-make[1]: Entering directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7ltnyt'
        mingw32-make[1]: *** No rule to make target 'C:/Users/Outros/3┬║Ano-2┬║Semestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeCCompilerABI.c', needed by 'CMakeFiles/cmTC_addd9.dir/CMakeCCompilerABI.c.obj'.  Stop.
        mingw32-make[1]: Leaving directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-7ltnyt'
        mingw32-make: *** [Makefile:126: cmTC_addd9/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Outros/3\u00baAno-2\u00baSemestre/DA/Aula 1/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/JetBrains/CLion 2022.2.4/bin/mingw/bin/gcc.exe"
    directories:
      source: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-y2pwou"
      binary: "//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-y2pwou"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-y2pwou'
        
        Run Build Command(s): "C:/Users/Outros/3ºAno-2ºSemestre/DA/Aula 1/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_d4f2f/fast
        C:/PROGRA~1/JETBRA~1/CLION2~1.4/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_d4f2f.dir\\build.make CMakeFiles/cmTC_d4f2f.dir/build
        mingw32-make[1]: Entering directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-y2pwou'
        process_begin: CreateProcess(NULL, "C:\\Users\\Outros\\3┬║Ano-2┬║Semestre\\DA\\Aula 1\\bin\\cmake.exe" -E cmake_echo_color --switch= --progress-dir=\\\\wsl$\\Ubuntu-20.04\\root\\1st_DAProject\\1stDA_Project\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-y2pwou\\CMakeFiles --progress-num=1 "Building C object CMakeFiles/cmTC_d4f2f.dir/testCCompiler.c.obj", ...) failed.
        make (e=2): O sistema nÒo conseguiu localizar o ficheiro especificado.\x0d
        mingw32-make[1]: *** [CMakeFiles\\cmTC_d4f2f.dir\\build.make:76: CMakeFiles/cmTC_d4f2f.dir/testCCompiler.c.obj] Error 2
        mingw32-make[1]: Leaving directory '//wsl$/Ubuntu-20.04/root/1st_DAProject/1stDA_Project/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-y2pwou'
        mingw32-make: *** [Makefile:126: cmTC_d4f2f/fast] Error 2
        
      exitCode: 2
...
